name: Hello world
on: 
 push:
   braches:
     - main
 pull_request:
   branches:
     - main

jobs:
  hello:
   runs-on: ubuntu-latest
   steps:
    - name: Hello step
      run: echo "Hello, ${{vars.MY_NAME}}"
       
  
