name: Hello world
on: 
 push:
   braches:
     - main
 pull_request:
   branches:
     - main

jobs:
  hello:
   runs-on: ubuntu-latest
   steps:
    - name: Hello step
      run: |
        echo "one"
        echo "two"
  test:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: test step
        run: echo "test"
